version: "3.9"
services:
  mongodb:
    image: mongo:5.0.15
    container_name: project2_login_mongodb
    ports:
      - "27017:27017"
    volumes:
      # - "./config/mongod.conf:/data/configdb/mongod.conf"
      - "./data:/data/db"
      - "./log:/var/log/mongodb"
    # command: ["/usr/bin/mongod", "-f", "/data/configdb/mongod.conf"]
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hadat
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=login_service
    
    # command: [mongo -u hadat -p admin --authenticationDatabase admin]
    networks:
      - login_service_mongodb

  api:
    build:
      dockerfile: Dockerfile.dev
    image: test_thesis_2_1:latest
    restart: always
    container_name: api_login_service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    # environment:
    #   WAIT_HOSTS: mongodb:27017
    #   MDB_HOST: mongodb
    #   MDB_PORT: 27017
    #   MDB_DATABASE: login_service
    networks:
      - login_service_mongodb
      - nginx_to_services

  nginx_proxy:

    image: nginx:latest
    container_name: nginx_reverse
    ports:
      - "80:80"
    volumes:
      # - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    restart: always
    depends_on:
      - api

    environment:
      # - NGINX_HOST=localhost
      - NGINX_PORT=80

    networks:
      - nginx_to_services
    
  
volumes:
  data:
  nginx_proxy:
  log: null

networks:
  login_service_mongodb:
    driver: bridge
  
  nginx_to_services:
    driver: bridge
